"""
Trading Signals

Data structures for representing trading signals generated by the scanner.
"""

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Optional, List
from enum import Enum


class SetupType(Enum):
    """Type of trading setup."""
    EP = "ep"  # Episodic Pivot
    BREAKOUT = "breakout"
    FLAG = "flag"
    HTF = "htf"  # High Tight Flag


@dataclass
class Signal:
    """A trading signal generated by the scanner."""
    symbol: str
    setup_type: SetupType
    entry_price: Decimal
    tactical_stop: Decimal  # KK-style: opening range low or flag low
    quality_score: int  # 1-10
    tier: str  # FOCUS, WIDE, SKIP
    rs_percentile: int  # Relative strength vs market
    adr_percent: float  # Average daily range
    
    # KK-style dual stops
    invalidation_level: Optional[Decimal] = None  # EP candle low (setup dead if breached)
    atr_at_entry: Optional[Decimal] = None  # ATR at signal generation
    
    # Metadata
    generated_at: datetime = None
    scanner_mode: str = "gainers"
    
    def __post_init__(self):
        if self.generated_at is None:
            self.generated_at = datetime.utcnow()
    
    @property
    def stop_distance(self) -> Decimal:
        """Distance from entry to stop."""
        return self.entry_price - self.tactical_stop
    
    @property
    def stop_percent(self) -> float:
        """Stop distance as percentage of entry."""
        if self.entry_price == 0:
            return 0
        return float((self.stop_distance / self.entry_price) * 100)
    
    @property
    def stop_atr(self) -> float:
        """Stop distance in ATR units (KK uses 1.0-1.5 ATR max)."""
        if self.atr_at_entry is None or self.atr_at_entry == 0:
            return 0
        return float(self.stop_distance / self.atr_at_entry)
    
    def calculate_shares(self, risk_dollars: Decimal) -> int:
        """Calculate position size based on risk."""
        if self.stop_distance <= 0:
            return 0
        # Ensure Decimal types for safe division
        risk = Decimal(str(risk_dollars)) if not isinstance(risk_dollars, Decimal) else risk_dollars
        stop_dist = Decimal(str(self.stop_distance)) if not isinstance(self.stop_distance, Decimal) else self.stop_distance
        return int(risk / stop_dist)
    
    def is_valid(
        self, 
        min_quality: int = 7,
        stop_mode: str = "atr",
        max_stop_atr: float = 1.0,
        max_stop_percent: float = 5.0,
    ) -> bool:
        """
        Check if signal meets filtering criteria.
        
        Args:
            min_quality: Minimum quality score (1-10)
            stop_mode: "atr" (KK-style) or "percent"
            max_stop_atr: Maximum stop distance in ATR units
            max_stop_percent: Maximum stop distance as percentage
        """
        # Base checks
        if self.quality_score < min_quality:
            return False
        if self.tier.upper() not in ("FOCUS", "WIDE"):
            return False
        if self.stop_distance <= 0:
            return False
        
        # Stop filter based on mode
        if stop_mode == "atr":
            # KK-style: stop must be within ATR limit
            if self.atr_at_entry is None or self.atr_at_entry == 0:
                # If no ATR data, fall back to percent
                return self.stop_percent <= max_stop_percent
            return self.stop_atr <= max_stop_atr
        else:
            # Percent mode
            return self.stop_percent <= max_stop_percent
    
    def get_rejection_reason(
        self,
        min_quality: int = 7,
        stop_mode: str = "atr",
        max_stop_atr: float = 1.0,
        max_stop_percent: float = 5.0,
    ) -> Optional[tuple]:
        """
        Get reason why signal would be filtered.
        
        Returns:
            (reason, threshold, actual_value) if rejected, None if valid
        """
        if self.quality_score < min_quality:
            return ("quality_too_low", min_quality, self.quality_score)
        if self.tier.upper() not in ("FOCUS", "WIDE"):
            return ("tier_not_focus_wide", 0, self.tier)
        if self.stop_distance <= 0:
            return ("no_stop_distance", 0, float(self.stop_distance))
        
        if stop_mode == "atr":
            if self.atr_at_entry is None or self.atr_at_entry == 0:
                if self.stop_percent > max_stop_percent:
                    return ("stop_too_wide_percent", max_stop_percent, self.stop_percent)
            elif self.stop_atr > max_stop_atr:
                return ("stop_too_wide_atr", max_stop_atr, self.stop_atr)
        else:
            if self.stop_percent > max_stop_percent:
                return ("stop_too_wide_percent", max_stop_percent, self.stop_percent)
        
        return None  # Valid


class SignalGenerator:
    """Converts scanner results to trading signals."""
    
    def __init__(self, min_quality: int = 7, max_stop_percent: float = 5.0):
        self.min_quality = min_quality
        self.max_stop_percent = max_stop_percent
    
    def from_scanner_result(self, result: dict, mode: str = "gainers") -> Optional[Signal]:
        """
        Convert a scanner result to a Signal.
        
        Args:
            result: Scanner result dict with symbol, price, quality_score, etc.
            mode: Scanner mode (gainers, actives, trend_leaders)
            
        Returns:
            Signal if valid, None if filtered out
        """
        # Determine setup type from scanner mode
        setup_type = {
            "gainers": SetupType.EP,
            "actives": SetupType.BREAKOUT,
            "trend_leaders": SetupType.FLAG,
        }.get(mode, SetupType.EP)
        
        # Calculate tactical stop (default 3% below entry)
        entry_price = Decimal(str(result.get("price", 0)))
        stop_percent = Decimal("0.03")  # 3% default
        tactical_stop = entry_price * (1 - stop_percent)
        
        signal = Signal(
            symbol=result.get("symbol", ""),
            setup_type=setup_type,
            entry_price=entry_price,
            tactical_stop=tactical_stop,
            quality_score=result.get("quality_score", 0),
            tier=result.get("tier", "SKIP"),
            rs_percentile=result.get("rs_percentile", 0),
            adr_percent=float(result.get("adr_percent", 0)),
            scanner_mode=mode,
        )
        
        # Filter out invalid signals
        if not signal.is_valid(self.min_quality):
            return None
        
        if signal.stop_percent > self.max_stop_percent:
            return None
        
        return signal
    
    def from_scanner_results(self, results: List, mode: str = "gainers") -> List[Signal]:
        """Convert multiple scanner results to signals.
        
        Handles both:
        - Signal objects (from UnifiedScanResult.signals)
        - Dict results (from raw scanner output)
        """
        signals = []
        for result in results:
            # Check if already a Signal object
            if isinstance(result, Signal):
                # Already a Signal - just validate it
                if result.is_valid(self.min_quality):
                    if result.stop_percent <= self.max_stop_percent:
                        signals.append(result)
            else:
                # Dict - convert to Signal
                signal = self.from_scanner_result(result, mode)
                if signal:
                    signals.append(signal)
        return signals
